package com.example.searchbar.ui.theme

import androidx.compose.ui.graphics.Color

val searchBarLightPrimary = Color(0xFF825500)
val searchBarLightOnPrimary = Color(0xFFFFFFFF)
val searchBarLightPrimaryContainer = Color(0xFFFFDDAE)
val searchBarLightOnPrimaryContainer = Color(0xFF2A1800)
val searchBarLightSecondary = Color(0xFF6F5B40)
val searchBarLightOnSecondary = Color(0xFFFFFFFF)
val searchBarLightSecondaryContainer = Color(0xFFFADEBC)
val searchBarLightOnSecondaryContainer = Color(0xFF271904)
val searchBarLightTertiary = Color(0xFF516440)
val searchBarLightOnTertiary = Color(0xFFFFFFFF)
val searchBarLightTertiaryContainer = Color(0xFFD3EABC)
val searchBarLightOnTertiaryContainer = Color(0xFF102004)
val searchBarLightError = Color(0xFFBA1B1B)
val searchBarLightErrorContainer = Color(0xFFFFDAD4)
val searchBarLightOnError = Color(0xFFFFFFFF)
val searchBarLightOnErrorContainer = Color(0xFF410001)
val searchBarLightBackground = Color(0xFFFCFCFC)
val searchBarLightOnBackground = Color(0xFF1F1B16)
val searchBarLightSurface = Color(0xFFFCFCFC)
val searchBarLightOnSurface = Color(0xFF1F1B16)
val searchBarLightSurfaceVariant = Color(0xFFF0E0CF)
val searchBarLightOnSurfaceVariant = Color(0xFF4F4539)
val searchBarLightOutline = Color(0xFF817567)
val searchBarLightInverseOnSurface = Color(0xFFF9EFE6)
val searchBarLightInverseSurface = Color(0xFF34302A)
val searchBarLightPrimaryInverse = Color(0xFFFFB945)

val searchBarDarkPrimary = Color(0xFFFFB945)
val searchBarDarkOnPrimary = Color(0xFF452B00)
val searchBarDarkPrimaryContainer = Color(0xFF624000)
val searchBarDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val searchBarDarkSecondary = Color(0xFFDDC3A2)
val searchBarDarkOnSecondary = Color(0xFF3E2E16)
val searchBarDarkSecondaryContainer = Color(0xFF56442B)
val searchBarDarkOnSecondaryContainer = Color(0xFFFADEBC)
val searchBarDarkTertiary = Color(0xFFB8CEA2)
val searchBarDarkOnTertiary = Color(0xFF243516)
val searchBarDarkTertiaryContainer = Color(0xFF3A4C2B)
val searchBarDarkOnTertiaryContainer = Color(0xFFD3EABC)
val searchBarDarkError = Color(0xFFFFB4A9)
val searchBarDarkErrorContainer = Color(0xFF930006)
val searchBarDarkOnError = Color(0xFF680003)
val searchBarDarkOnErrorContainer = Color(0xFFFFDAD4)
val searchBarDarkBackground = Color(0xFF1F1B16)
val searchBarDarkOnBackground = Color(0xFFEAE1D9)
val searchBarDarkSurface = Color(0xFF1F1B16)
val searchBarDarkOnSurface = Color(0xFFEAE1D9)
val searchBarDarkSurfaceVariant = Color(0xFF4F4539)
val searchBarDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val searchBarDarkOutline = Color(0xFF9C8F80)
val searchBarDarkInverseOnSurface = Color(0xFF32281A)
val searchBarDarkInverseSurface = Color(0xFFEAE1D9)
val searchBarDarkPrimaryInverse = Color(0xFF624000)
